import type { InspirationItem } from "./types"

export const SAMPLE_INSPIRATION: InspirationItem[] = [
  {
    id: "insp-1",
    title: "Granola — AI Meeting Notepad",
    creator: "Chris Pedregal",
    description:
      "An AI notepad that listens to your meetings and enhances your rough notes into polished summaries. Not a transcription tool — it augments what you actually write.",
    why_notable:
      "Nailed the UX problem that transcription tools missed: people want to write their own notes, just better. $10M ARR in under a year as a solo-ish product.",
    category: "product",
    image_url: null,
    source_url: "https://www.granola.so",
    source: "Product Hunt",
    tags: ["ai", "productivity", "saas"],
    build_this: true,
    created_at: "2026-02-27T08:00:00Z",
    tech_stack: ["Electron", "Whisper API", "React", "Node.js", "OpenAI GPT-4"],
    links: [
      { label: "Website", url: "https://www.granola.so" },
      { label: "Product Hunt", url: "https://www.producthunt.com/products/granola" },
    ],
    key_features: [
      "Real-time audio capture during meetings",
      "AI-enhanced note completion from rough bullet points",
      "Automatic action item extraction",
      "Integrates with Google Meet, Zoom, and Teams",
    ],
    revenue_or_traction: "$10M ARR in under 12 months",
  },
  {
    id: "insp-2",
    title: "Generative Aurora Shader",
    creator: "@spite",
    description:
      "A real-time WebGL shader that generates aurora borealis effects using noise fields and chromatic aberration. Runs at 120fps on mobile.",
    why_notable:
      "Proves that generative art can be both computationally elegant and visually stunning. The color blending algorithm is genius-level math made visual.",
    category: "creative_tech",
    image_url: null,
    source_url: "https://github.com/spite/aurora-shader",
    source: "Twitter/X",
    tags: ["webgl", "generative-art", "shaders"],
    build_this: false,
    created_at: "2026-02-27T07:30:00Z",
    tech_stack: ["WebGL 2.0", "GLSL", "Three.js", "JavaScript"],
    links: [
      { label: "Live Demo", url: "https://spite.github.io/aurora-shader" },
      { label: "GitHub", url: "https://github.com/spite/aurora-shader" },
      { label: "Twitter Thread", url: "https://x.com/spite/status/example" },
    ],
    key_features: [
      "Perlin noise-driven aurora wave simulation",
      "Real-time chromatic aberration post-processing",
      "120fps on mobile with adaptive quality",
      "Configurable color palettes and wave intensity",
    ],
    revenue_or_traction: null,
  },
  {
    id: "insp-3",
    title: "Linear's 2026 Redesign",
    creator: "Linear Team",
    description:
      "Complete redesign featuring fluid spring animations, contextual command menus, and a spatial canvas view for project planning. Every interaction feels intentional.",
    why_notable:
      "Set a new bar for what a SaaS dashboard can feel like. The micro-interactions and transitions make enterprise software feel like a creative tool.",
    category: "ui_design",
    image_url: null,
    source_url: "https://linear.app",
    source: "Twitter/X",
    tags: ["design-system", "animations", "saas"],
    build_this: false,
    created_at: "2026-02-26T22:00:00Z",
    tech_stack: ["React", "Framer Motion", "TypeScript", "Next.js", "Custom Spring Physics"],
    links: [
      { label: "Website", url: "https://linear.app" },
      { label: "Design Blog", url: "https://linear.app/blog/redesign-2026" },
    ],
    key_features: [
      "Spring-physics-based transitions on every element",
      "Spatial canvas view for project planning",
      "Contextual command palette with fuzzy search",
      "Multi-layered glass depth system",
      "Sub-pixel animation precision",
    ],
    revenue_or_traction: "Series B, used by 10K+ teams",
  },
  {
    id: "insp-4",
    title: "Doodle-to-Game Engine",
    creator: "@maxbittker",
    description:
      "Draw a rough sketch on paper, point your phone camera at it, and the AI turns it into a playable 2D platformer in real-time. Characters, physics, and everything.",
    why_notable:
      "The most creative use of multimodal AI I've seen. Takes the 'AI generates code' idea and makes it tactile and fun. Kids go absolutely wild with it.",
    category: "creative_tech",
    image_url: null,
    source_url: "https://github.com/maxbittker/doodle-game",
    source: "GitHub",
    tags: ["ai", "games", "computer-vision"],
    build_this: true,
    created_at: "2026-02-26T18:00:00Z",
    tech_stack: ["Claude Vision API", "React Native", "Matter.js", "Canvas API", "Python backend"],
    links: [
      { label: "GitHub", url: "https://github.com/maxbittker/doodle-game" },
      { label: "Demo Video", url: "https://youtube.com/watch?v=example" },
    ],
    key_features: [
      "Real-time sketch-to-game conversion via phone camera",
      "AI-generated physics properties based on drawn shapes",
      "Character detection and automatic sprite animation",
      "Multiplayer mode — each player draws their own character",
    ],
    revenue_or_traction: "12K GitHub stars, featured at GDC 2026",
  },
  {
    id: "insp-5",
    title: "Raycast-Style Command Palette Site",
    creator: "@emilkowalski_",
    description:
      "A personal portfolio built entirely around a command palette interface. Navigate everything with keyboard shortcuts, fuzzy search, and contextual actions.",
    why_notable:
      "Rethinks what a personal website can be. Zero scrolling, pure intent-driven navigation. The spring animations and blur effects are pixel-perfect.",
    category: "ui_design",
    image_url: null,
    source_url: "https://emilkowal.ski",
    source: "Twitter/X",
    tags: ["portfolio", "command-palette", "animations"],
    build_this: true,
    created_at: "2026-02-26T15:00:00Z",
    tech_stack: ["Next.js 15", "Framer Motion", "Tailwind CSS", "cmdk", "Vercel"],
    links: [
      { label: "Live Site", url: "https://emilkowal.ski" },
      { label: "Twitter Thread", url: "https://x.com/emilkowalski_/status/example" },
      { label: "GitHub", url: "https://github.com/emilkowalski/portfolio" },
    ],
    key_features: [
      "Full keyboard-driven navigation with fuzzy search",
      "Spring-physics animations on every transition",
      "Contextual action menus per content type",
      "Sub-50ms input response time",
      "Beautiful blur-layered glass depth system",
    ],
    revenue_or_traction: null,
  },
  {
    id: "insp-6",
    title: "AI Product Photoshoot Studio",
    creator: "Flair AI",
    description:
      "Upload a product photo and generate studio-quality lifestyle shots with custom backgrounds, lighting, and styling. Replaces $5K photoshoots with a $20/mo subscription.",
    why_notable:
      "Solves a real pain point for e-commerce sellers. The quality gap between AI-generated and real photography has essentially closed for product shots.",
    category: "product",
    image_url: null,
    source_url: "https://flair.ai",
    source: "Product Hunt",
    tags: ["ai", "e-commerce", "image-generation"],
    build_this: true,
    created_at: "2026-02-26T12:00:00Z",
    tech_stack: ["Stable Diffusion XL", "ControlNet", "Python", "React", "AWS Lambda"],
    links: [
      { label: "Website", url: "https://flair.ai" },
      { label: "Product Hunt", url: "https://www.producthunt.com/products/flair-ai" },
    ],
    key_features: [
      "One-click background removal and replacement",
      "AI-generated lighting and shadow matching",
      "Brand kit with saved styles and templates",
      "Batch processing for product catalogs",
      "Custom scene generation from text prompts",
    ],
    revenue_or_traction: "$2M ARR, 50K+ active users",
  },
  {
    id: "insp-7",
    title: "Spatial Music Visualizer",
    creator: "@mattdesl",
    description:
      "A 3D audio visualizer that creates real-time spatial environments from music. Frequencies map to terrain, rhythm drives camera movement, vocals generate particle trails.",
    why_notable:
      "Creative coding at its finest. Uses Web Audio API analysis piped into Three.js with custom post-processing. The synesthesia effect is mesmerizing.",
    category: "creative_tech",
    image_url: null,
    source_url: "https://codepen.io/mattdesl/pen/spatial-audio",
    source: "CodePen",
    tags: ["three.js", "audio", "creative-coding"],
    build_this: false,
    created_at: "2026-02-25T20:00:00Z",
    tech_stack: ["Three.js", "Web Audio API", "GLSL Shaders", "JavaScript", "Tone.js"],
    links: [
      { label: "CodePen", url: "https://codepen.io/mattdesl/pen/spatial-audio" },
      { label: "GitHub", url: "https://github.com/mattdesl/spatial-visualizer" },
    ],
    key_features: [
      "FFT frequency analysis mapped to 3D terrain generation",
      "Beat detection drives camera movement and cuts",
      "Vocal isolation creates particle trail systems",
      "Custom GLSL bloom and chromatic aberration post-processing",
    ],
    revenue_or_traction: null,
  },
  {
    id: "insp-8",
    title: "Glass Morphism Dashboard Kit",
    creator: "@juxtopposed",
    description:
      "Open-source dashboard component library featuring layered glass effects, dynamic blur depths, and gradient mesh backgrounds. Everything animates with spring physics.",
    why_notable:
      "The glass layering technique is genuinely novel — multiple blur depths create a sense of z-space that flat design can't achieve. Gorgeous on dark mode.",
    category: "ui_design",
    image_url: null,
    source_url: "https://github.com/juxtopposed/glass-dashboard",
    source: "GitHub",
    tags: ["glassmorphism", "components", "open-source"],
    build_this: false,
    created_at: "2026-02-25T16:00:00Z",
    tech_stack: ["React", "Tailwind CSS", "Framer Motion", "Radix UI", "TypeScript"],
    links: [
      { label: "GitHub", url: "https://github.com/juxtopposed/glass-dashboard" },
      { label: "Live Demo", url: "https://glass-dashboard.vercel.app" },
      { label: "Figma Kit", url: "https://figma.com/community/file/example" },
    ],
    key_features: [
      "Multi-depth blur layering for z-space illusion",
      "Dynamic gradient mesh backgrounds",
      "Spring-physics-based component transitions",
      "20+ pre-built dashboard components",
      "Dark mode optimized with variable opacity",
    ],
    revenue_or_traction: "8K GitHub stars, 500+ Figma duplicates",
  },
  {
    id: "insp-9",
    title: "Voice-First CRM for Freelancers",
    creator: "IndieHacker @sarah_codes",
    description:
      "A CRM where you just talk about your client interactions and it automatically creates contacts, logs notes, sets follow-ups, and tracks deals. Zero manual data entry.",
    why_notable:
      "Flips the CRM model on its head. Instead of filling forms, you just narrate your day. Hit $8K MRR in 3 months. The NLP pipeline for extracting structured data from casual speech is impressive.",
    category: "product",
    image_url: null,
    source_url: null,
    source: "Indie Hackers",
    tags: ["ai", "crm", "voice", "indie"],
    build_this: true,
    created_at: "2026-02-25T10:00:00Z",
    tech_stack: ["Whisper", "GPT-4 Turbo", "Next.js", "Supabase", "Stripe", "React Native"],
    links: [
      { label: "Indie Hackers Post", url: "https://indiehackers.com/product/voicecrm" },
    ],
    key_features: [
      "Voice-to-CRM pipeline with entity extraction",
      "Automatic contact creation from mentioned names",
      "Smart follow-up scheduling from casual mentions",
      "Deal pipeline tracking inferred from conversations",
      "Daily digest email with AI-summarized interactions",
    ],
    revenue_or_traction: "$8K MRR in 3 months, 400+ paying users",
  },
  {
    id: "insp-10",
    title: "Terminal That Looks Like a Spaceship",
    creator: "@warp_dev",
    description:
      "A custom terminal emulator themed like a sci-fi spaceship cockpit. HUD-style overlays, holographic syntax highlighting, and command history displayed as a star map.",
    why_notable:
      "Pure joy engineering. Zero commercial purpose, maximum vibes. The attention to detail in the animations — from the boot sequence to the cursor glow — is insane.",
    category: "creative_tech",
    image_url: null,
    source_url: "https://github.com/warp-dev/spaceship-terminal",
    source: "Twitter/X",
    tags: ["terminal", "sci-fi", "design"],
    build_this: false,
    created_at: "2026-02-24T22:00:00Z",
    tech_stack: ["Rust", "WebGPU", "WGSL Shaders", "TypeScript", "Tauri"],
    links: [
      { label: "GitHub", url: "https://github.com/warp-dev/spaceship-terminal" },
      { label: "Twitter Thread", url: "https://x.com/warp_dev/status/example" },
      { label: "Demo Video", url: "https://youtube.com/watch?v=example" },
    ],
    key_features: [
      "Custom boot sequence animation with sound design",
      "HUD-style overlays for system stats",
      "Command history visualized as navigable star map",
      "Holographic syntax highlighting with depth layers",
      "GPU-accelerated rendering via WebGPU",
    ],
    revenue_or_traction: null,
  },
]
