import type { MindItem } from "@/lib/types"

function daysAgo(n: number): string {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString()
}

export const SAMPLE_MIND_ITEMS: MindItem[] = [
  // ── Row 1: screenshot, article, thought ──
  {
    id: "mind-1",
    type: "screenshot",
    title: "Vercel Dashboard — Deployment Pipeline",
    content: "Screenshot of Vercel deployment dashboard showing build logs, preview deployments, and edge function metrics for the command center project.",
    summary: "Vercel deployment dashboard with build pipeline and edge function performance metrics.",
    url: "https://vercel.com/dashboard",
    source_domain: "vercel.com",
    image_url: null,
    language: null,
    tags: ["vercel", "deployment", "devops", "monitoring"],
    access_count: 4,
    last_accessed_at: daysAgo(0),
    created_at: daysAgo(1),
  },
  {
    id: "mind-2",
    type: "article",
    title: "Designing Data-Intensive Applications — Key Takeaways",
    content: "Martin Kleppmann's masterpiece on distributed systems. Key concepts: replication strategies (single-leader, multi-leader, leaderless), partitioning schemes (key range vs hash), consistency models (linearizability, causal, eventual).",
    summary: "Core concepts from DDIA covering replication, partitioning, consistency models, and the stream vs batch processing paradigm shift.",
    url: "https://dataintensive.net/",
    source_domain: "dataintensive.net",
    image_url: null,
    language: null,
    tags: ["distributed-systems", "databases", "architecture"],
    access_count: 12,
    last_accessed_at: daysAgo(1),
    created_at: daysAgo(2),
  },
  {
    id: "mind-3",
    type: "thought",
    title: null,
    content: "What if the command center had a directive system where I could set standing orders for the AI agent? Like 'remind me to drink water if I haven't logged any by 3pm' or 'summarize any HN post about AI agents above 500 points'.",
    summary: "Idea for a directive system — standing orders that an AI agent evaluates continuously.",
    url: null,
    source_domain: null,
    image_url: null,
    language: null,
    tags: ["command-center", "ai-agent", "product-idea", "automation"],
    access_count: 5,
    last_accessed_at: daysAgo(0),
    created_at: daysAgo(3),
  },

  // ── Row 2: code, image, highlight ──
  {
    id: "mind-4",
    type: "code",
    title: "React useDebounce Hook",
    content: "import { useState, useEffect } from 'react'\n\nexport function useDebounce<T>(value: T, delay: number): T {\n  const [debouncedValue, setDebouncedValue] = useState<T>(value)\n\n  useEffect(() => {\n    const handler = setTimeout(() => setDebouncedValue(value), delay)\n    return () => clearTimeout(handler)\n  }, [value, delay])\n\n  return debouncedValue\n}",
    summary: "A reusable React hook for debouncing values with configurable delay.",
    url: "https://usehooks.com/usedebounce",
    source_domain: "usehooks.com",
    image_url: null,
    language: "typescript",
    tags: ["react", "hooks", "typescript", "debounce"],
    access_count: 8,
    last_accessed_at: daysAgo(2),
    created_at: daysAgo(4),
  },
  {
    id: "mind-5",
    type: "image",
    title: "Neural Network Architecture Diagram",
    content: "Transformer architecture visualization showing multi-head attention, feed-forward layers, and residual connections. Saved from a research paper on scaling laws.",
    summary: "Detailed transformer architecture diagram showing attention mechanisms and layer composition.",
    url: "https://arxiv.org/abs/1706.03762",
    source_domain: "arxiv.org",
    image_url: null,
    language: null,
    tags: ["ai", "transformers", "deep-learning", "research"],
    access_count: 6,
    last_accessed_at: daysAgo(2),
    created_at: daysAgo(5),
  },
  {
    id: "mind-6",
    type: "highlight",
    title: null,
    content: "The best architectures, requirements, and designs emerge from self-organizing teams. At regular intervals, the team reflects on how to become more effective, then tunes and adjusts its behavior accordingly.",
    summary: "Agile Manifesto principle on self-organizing teams and continuous improvement.",
    url: "https://agilemanifesto.org/principles.html",
    source_domain: "agilemanifesto.org",
    image_url: null,
    language: null,
    tags: ["agile", "architecture", "teams", "software-development"],
    access_count: 3,
    last_accessed_at: daysAgo(5),
    created_at: daysAgo(6),
  },

  // ── Row 3: thought, screenshot, article ──
  {
    id: "mind-7",
    type: "thought",
    title: null,
    content: "Sleep is the single biggest lever on productivity. On days I sleep 7+ hours I complete 90% of habits. Under 6 hours it drops to 40%. Need to track this properly and correlate with everything else.",
    summary: "Personal observation linking sleep quality to habit completion rates.",
    url: null,
    source_domain: null,
    image_url: null,
    language: null,
    tags: ["sleep", "productivity", "habits", "health"],
    access_count: 2,
    last_accessed_at: daysAgo(1),
    created_at: daysAgo(7),
  },
  {
    id: "mind-8",
    type: "screenshot",
    title: "Supabase Table Editor — Mind Items Schema",
    content: "Screenshot of the Supabase table editor showing the mind_items table structure with vector column, tags array, and all indexes configured.",
    summary: "Supabase table editor showing mind_items schema with pgvector column and indexes.",
    url: "https://supabase.com/dashboard",
    source_domain: "supabase.com",
    image_url: null,
    language: null,
    tags: ["supabase", "database", "schema", "pgvector"],
    access_count: 2,
    last_accessed_at: daysAgo(0),
    created_at: daysAgo(8),
  },
  {
    id: "mind-9",
    type: "article",
    title: "PostgreSQL pgvector: Embeddings and Vector Similarity Search",
    content: "pgvector adds vector similarity search to Postgres. Store embeddings alongside your relational data. Supports L2 distance, inner product, and cosine distance.",
    summary: "Guide to using pgvector for embedding storage and similarity search directly in PostgreSQL.",
    url: "https://github.com/pgvector/pgvector",
    source_domain: "github.com",
    image_url: null,
    language: null,
    tags: ["postgresql", "pgvector", "embeddings", "vector-search"],
    access_count: 7,
    last_accessed_at: daysAgo(1),
    created_at: daysAgo(9),
  },

  // ── Row 4: highlight, code, image ──
  {
    id: "mind-10",
    type: "highlight",
    title: null,
    content: "Premature optimization is the root of all evil. Yet we should not pass up our opportunities in that critical 3%. A good programmer will not be lulled into complacency by such reasoning, he will be wise to look carefully at the critical code; but only after that code has been identified.",
    summary: "Donald Knuth's famous quote on optimization — the full context.",
    url: "https://wiki.c2.com/?PrematureOptimization",
    source_domain: "wiki.c2.com",
    image_url: null,
    language: null,
    tags: ["optimization", "programming", "wisdom", "knuth"],
    access_count: 6,
    last_accessed_at: daysAgo(4),
    created_at: daysAgo(10),
  },
  {
    id: "mind-11",
    type: "code",
    title: "Go Error Handling Pattern with Wrap",
    content: "func fetchUser(id string) (*User, error) {\n\tuser, err := db.QueryUser(id)\n\tif err != nil {\n\t\treturn nil, fmt.Errorf(\"fetchUser(%s): %w\", id, err)\n\t}\n\tif user == nil {\n\t\treturn nil, fmt.Errorf(\"fetchUser(%s): %w\", id, ErrNotFound)\n\t}\n\treturn user, nil\n}",
    summary: "Idiomatic Go error handling using fmt.Errorf with %w verb for error wrapping.",
    url: null,
    source_domain: null,
    image_url: null,
    language: "go",
    tags: ["go", "error-handling", "patterns", "best-practices"],
    access_count: 4,
    last_accessed_at: daysAgo(3),
    created_at: daysAgo(12),
  },
  {
    id: "mind-12",
    type: "image",
    title: "System Design Whiteboard — Event Sourcing",
    content: "Whiteboard photo from architecture session. Shows event store, projections, command handlers, and read models in an event-sourced system.",
    summary: "Whiteboard capture of event sourcing architecture with CQRS pattern.",
    url: null,
    source_domain: null,
    image_url: null,
    language: null,
    tags: ["system-design", "event-sourcing", "cqrs", "architecture"],
    access_count: 3,
    last_accessed_at: daysAgo(4),
    created_at: daysAgo(15),
  },

  // ── Row 5: article, thought, screenshot ──
  {
    id: "mind-13",
    type: "article",
    title: "The Twelve-Factor App",
    content: "A methodology for building software-as-a-service apps. Key factors: codebase, dependencies, config, backing services, build/release/run, processes, port binding, concurrency, disposability, dev/prod parity, logs, admin processes.",
    summary: "The 12 principles for building modern SaaS applications.",
    url: "https://12factor.net/",
    source_domain: "12factor.net",
    image_url: null,
    language: null,
    tags: ["architecture", "saas", "twelve-factor", "devops"],
    access_count: 9,
    last_accessed_at: daysAgo(2),
    created_at: daysAgo(18),
  },
  {
    id: "mind-14",
    type: "thought",
    title: null,
    content: "Building in public is underrated. Every time I share a work-in-progress screenshot, I get feedback that saves me days. The vulnerability of showing unfinished work is exactly what makes it powerful.",
    summary: "Reflection on the value of building in public and sharing work-in-progress.",
    url: null,
    source_domain: null,
    image_url: null,
    language: null,
    tags: ["building-in-public", "productivity", "reflection", "growth"],
    access_count: 1,
    last_accessed_at: daysAgo(2),
    created_at: daysAgo(20),
  },
  {
    id: "mind-15",
    type: "screenshot",
    title: "GitHub Actions — CI/CD Pipeline",
    content: "Screenshot of the GitHub Actions workflow runs showing test, lint, and deploy stages for the command center monorepo.",
    summary: "GitHub Actions CI/CD pipeline with test, lint, and deploy stages.",
    url: "https://github.com/actions",
    source_domain: "github.com",
    image_url: null,
    language: null,
    tags: ["github", "ci-cd", "devops", "testing"],
    access_count: 3,
    last_accessed_at: daysAgo(1),
    created_at: daysAgo(22),
  },

  // ── Row 6: image, highlight, code ──
  {
    id: "mind-16",
    type: "image",
    title: "Color Palette — Command Center Dark Theme",
    content: "Figma screenshot of the color palette exploration for the command center dark theme. Space-900 through 600, cosmic, electric, amber accent families.",
    summary: "Dark theme color palette with cosmic and electric accent families.",
    url: null,
    source_domain: null,
    image_url: null,
    language: null,
    tags: ["design", "color-palette", "dark-theme", "ui"],
    access_count: 5,
    last_accessed_at: daysAgo(3),
    created_at: daysAgo(25),
  },
  {
    id: "mind-17",
    type: "highlight",
    title: null,
    content: "Make it work, make it right, make it fast — in that order. The first step is getting something running. The second is refactoring for clarity and correctness. The third is optimizing, but only where measurement proves it necessary.",
    summary: "Kent Beck's development philosophy: functionality first, then correctness, then performance.",
    url: null,
    source_domain: null,
    image_url: null,
    language: null,
    tags: ["programming", "wisdom", "kent-beck", "refactoring"],
    access_count: 5,
    last_accessed_at: daysAgo(3),
    created_at: daysAgo(28),
  },
  {
    id: "mind-18",
    type: "code",
    title: "Supabase pgvector Search Function",
    content: "create or replace function mind_search(\n  query_embedding vector(1536),\n  match_count int default 20\n)\nreturns table (\n  id uuid, type text, title text,\n  similarity float\n)\nlanguage plpgsql as $$\nbegin\n  return query\n  select mi.id, mi.type, mi.title,\n    1 - (mi.embedding <=> query_embedding) as similarity\n  from mind_items mi\n  where mi.embedding is not null\n  order by mi.embedding <=> query_embedding\n  limit match_count;\nend;\n$$;",
    summary: "PostgreSQL function for semantic search using pgvector cosine similarity.",
    url: null,
    source_domain: null,
    image_url: null,
    language: "sql",
    tags: ["postgresql", "pgvector", "supabase", "search"],
    access_count: 3,
    last_accessed_at: daysAgo(0),
    created_at: daysAgo(30),
  },
]
