import type { MindItem } from "@/lib/types"

function daysAgo(n: number): string {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString()
}

export const SAMPLE_MIND_ITEMS: MindItem[] = [
  {
    id: "mind-1",
    type: "article",
    title: "Designing Data-Intensive Applications — Key Takeaways",
    content: "Martin Kleppmann's masterpiece on distributed systems. Key concepts: replication strategies (single-leader, multi-leader, leaderless), partitioning schemes (key range vs hash), consistency models (linearizability, causal, eventual). The section on stream processing vs batch processing fundamentally changed how I think about data pipelines.",
    summary: "Core concepts from DDIA covering replication, partitioning, consistency models, and the stream vs batch processing paradigm shift.",
    url: "https://dataintensive.net/",
    source_domain: "dataintensive.net",
    image_url: null,
    language: null,
    tags: ["distributed-systems", "databases", "architecture", "replication", "consistency"],
    access_count: 12,
    last_accessed_at: daysAgo(1),
    created_at: daysAgo(14),
  },
  {
    id: "mind-2",
    type: "code",
    title: "React useDebounce Hook",
    content: "import { useState, useEffect } from 'react'\n\nexport function useDebounce<T>(value: T, delay: number): T {\n  const [debouncedValue, setDebouncedValue] = useState<T>(value)\n\n  useEffect(() => {\n    const handler = setTimeout(() => setDebouncedValue(value), delay)\n    return () => clearTimeout(handler)\n  }, [value, delay])\n\n  return debouncedValue\n}",
    summary: "A reusable React hook for debouncing values with configurable delay. Useful for search inputs and API calls.",
    url: "https://usehooks.com/usedebounce",
    source_domain: "usehooks.com",
    image_url: null,
    language: "typescript",
    tags: ["react", "hooks", "typescript", "debounce", "performance"],
    access_count: 8,
    last_accessed_at: daysAgo(2),
    created_at: daysAgo(10),
  },
  {
    id: "mind-3",
    type: "highlight",
    title: null,
    content: "The best architectures, requirements, and designs emerge from self-organizing teams. At regular intervals, the team reflects on how to become more effective, then tunes and adjusts its behavior accordingly.",
    summary: "Agile Manifesto principle on self-organizing teams and continuous improvement through regular reflection.",
    url: "https://agilemanifesto.org/principles.html",
    source_domain: "agilemanifesto.org",
    image_url: null,
    language: null,
    tags: ["agile", "architecture", "teams", "software-development"],
    access_count: 3,
    last_accessed_at: daysAgo(5),
    created_at: daysAgo(21),
  },
  {
    id: "mind-4",
    type: "thought",
    title: null,
    content: "What if the command center had a directive system where I could set standing orders for the AI agent? Like 'remind me to drink water if I haven't logged any by 3pm' or 'summarize any HN post about AI agents above 500 points'. The agent evaluates these continuously.",
    summary: "Idea for a directive system — standing orders that an AI agent evaluates continuously, with triggers and escalation ladders.",
    url: null,
    source_domain: null,
    image_url: null,
    language: null,
    tags: ["command-center", "ai-agent", "product-idea", "directives", "automation"],
    access_count: 5,
    last_accessed_at: daysAgo(0),
    created_at: daysAgo(3),
  },
  {
    id: "mind-5",
    type: "article",
    title: "PostgreSQL pgvector: Embeddings and Vector Similarity Search",
    content: "pgvector adds vector similarity search to Postgres. Store embeddings alongside your relational data. Supports L2 distance, inner product, and cosine distance. Use IVFFlat index for approximate nearest neighbor search on large datasets. Key insight: you don't need a separate vector database — Postgres can handle thousands of vectors efficiently with proper indexing.",
    summary: "Guide to using pgvector for embedding storage and similarity search directly in PostgreSQL, eliminating the need for a separate vector database.",
    url: "https://github.com/pgvector/pgvector",
    source_domain: "github.com",
    image_url: null,
    language: null,
    tags: ["postgresql", "pgvector", "embeddings", "vector-search", "rag", "database"],
    access_count: 7,
    last_accessed_at: daysAgo(1),
    created_at: daysAgo(7),
  },
  {
    id: "mind-6",
    type: "code",
    title: "Go Error Handling Pattern with Wrap",
    content: "func fetchUser(id string) (*User, error) {\n\tuser, err := db.QueryUser(id)\n\tif err != nil {\n\t\treturn nil, fmt.Errorf(\"fetchUser(%s): %w\", id, err)\n\t}\n\tif user == nil {\n\t\treturn nil, fmt.Errorf(\"fetchUser(%s): %w\", id, ErrNotFound)\n\t}\n\treturn user, nil\n}",
    summary: "Idiomatic Go error handling using fmt.Errorf with %w verb for error wrapping, preserving error chain for errors.Is/As checks.",
    url: null,
    source_domain: null,
    image_url: null,
    language: "go",
    tags: ["go", "error-handling", "patterns", "best-practices"],
    access_count: 4,
    last_accessed_at: daysAgo(3),
    created_at: daysAgo(12),
  },
  {
    id: "mind-7",
    type: "highlight",
    title: null,
    content: "Premature optimization is the root of all evil. Yet we should not pass up our opportunities in that critical 3%. A good programmer will not be lulled into complacency by such reasoning, he will be wise to look carefully at the critical code; but only after that code has been identified.",
    summary: "Donald Knuth's famous quote on optimization — the full context emphasizing that the critical 3% still matters.",
    url: "https://wiki.c2.com/?PrematureOptimization",
    source_domain: "wiki.c2.com",
    image_url: null,
    language: null,
    tags: ["optimization", "programming", "wisdom", "knuth", "performance"],
    access_count: 6,
    last_accessed_at: daysAgo(4),
    created_at: daysAgo(30),
  },
  {
    id: "mind-8",
    type: "article",
    title: "The Twelve-Factor App",
    content: "A methodology for building software-as-a-service apps. Key factors: codebase (one repo, many deploys), dependencies (explicitly declare), config (store in environment), backing services (treat as attached resources), build/release/run (strictly separate stages), processes (stateless), port binding (export via port), concurrency (scale out via process model), disposability (fast startup, graceful shutdown), dev/prod parity, logs (treat as event streams), admin processes (run as one-off).",
    summary: "The 12 principles for building modern SaaS applications: from codebase management and dependency isolation to stateless processes and log streaming.",
    url: "https://12factor.net/",
    source_domain: "12factor.net",
    image_url: null,
    language: null,
    tags: ["architecture", "saas", "twelve-factor", "devops", "best-practices", "cloud"],
    access_count: 9,
    last_accessed_at: daysAgo(2),
    created_at: daysAgo(45),
  },
  {
    id: "mind-9",
    type: "thought",
    title: null,
    content: "Sleep is the single biggest lever on productivity. On days I sleep 7+ hours I complete 90% of habits. Under 6 hours it drops to 40%. Need to track this properly and correlate with everything else.",
    summary: "Personal observation linking sleep quality to habit completion rates, motivating the need for sleep tracking in the command center.",
    url: null,
    source_domain: null,
    image_url: null,
    language: null,
    tags: ["sleep", "productivity", "habits", "health", "personal-insight"],
    access_count: 2,
    last_accessed_at: daysAgo(1),
    created_at: daysAgo(5),
  },
  {
    id: "mind-10",
    type: "code",
    title: "Supabase pgvector Search Function",
    content: "create or replace function mind_search(\n  query_embedding vector(1536),\n  match_count int default 20\n)\nreturns table (\n  id uuid,\n  type text,\n  title text,\n  content text,\n  summary text,\n  url text,\n  source_domain text,\n  image_url text,\n  language text,\n  tags text[],\n  access_count int,\n  last_accessed_at timestamptz,\n  created_at timestamptz,\n  similarity float\n)\nlanguage plpgsql as $$\nbegin\n  return query\n  select\n    mi.id, mi.type, mi.title, mi.content, mi.summary,\n    mi.url, mi.source_domain, mi.image_url, mi.language,\n    mi.tags, mi.access_count, mi.last_accessed_at, mi.created_at,\n    1 - (mi.embedding <=> query_embedding) as similarity\n  from mind_items mi\n  where mi.embedding is not null\n  order by mi.embedding <=> query_embedding\n  limit match_count;\nend;\n$$;",
    summary: "PostgreSQL function for semantic search using pgvector cosine similarity, returning mind items ranked by embedding distance.",
    url: null,
    source_domain: null,
    image_url: null,
    language: "sql",
    tags: ["postgresql", "pgvector", "supabase", "search", "sql", "embeddings"],
    access_count: 3,
    last_accessed_at: daysAgo(0),
    created_at: daysAgo(2),
  },
  {
    id: "mind-11",
    type: "article",
    title: "Why We Sleep — Matthew Walker",
    content: "Sleep is the single most effective thing we can do to reset our brain and body health each day. Key findings: sleep deprivation after learning reduces memory retention by 40%. The brain's glymphatic system clears toxic waste (including beta-amyloid) during deep sleep. REM sleep is critical for emotional regulation and creativity. Even modest sleep reduction (6 hours instead of 8) impairs immune function measurably within a week.",
    summary: "Key findings from Matthew Walker's research on sleep: memory consolidation, brain waste clearance, immune function, and why 6 hours isn't enough.",
    url: "https://www.sleepdiplomat.com/",
    source_domain: "sleepdiplomat.com",
    image_url: null,
    language: null,
    tags: ["sleep", "health", "neuroscience", "book", "productivity"],
    access_count: 4,
    last_accessed_at: daysAgo(6),
    created_at: daysAgo(20),
  },
  {
    id: "mind-12",
    type: "highlight",
    title: null,
    content: "Make it work, make it right, make it fast — in that order. The first step is getting something running. The second is refactoring for clarity and correctness. The third is optimizing, but only where measurement proves it necessary.",
    summary: "Kent Beck's development philosophy: functionality first, then correctness through refactoring, then performance optimization guided by measurement.",
    url: null,
    source_domain: null,
    image_url: null,
    language: null,
    tags: ["programming", "wisdom", "kent-beck", "refactoring", "optimization"],
    access_count: 5,
    last_accessed_at: daysAgo(3),
    created_at: daysAgo(60),
  },
]
